//! Hand-maintained manifest of which clap builder tests we have addressed.
//! Each entry references a test in tests/clap_universe.zig:
//!   - `ported`   — translated and passing in a tests/clap_<file>_test.zig
//!   - `deferred` — needs a feature clap-zig hasn't implemented yet (see note)
//! Tests in the universe but absent here are still `pending`. Run
//! `zig build coverage` for the report. The goal is zero pending: every test is
//! either ported or deferred, i.e. 100% of what we support.

pub const Status = enum { ported, deferred };

pub const Entry = struct {
    file: []const u8,
    name: []const u8,
    status: Status,
    /// for `deferred`: the missing feature gating this test
    note: []const u8 = "",
};

pub const entries = [_]Entry{
    // ----- version (long_version / propagate_version / -V vs --version) -----
    .{ .file = "version.rs", .name = "version_short_flag_no_version", .status = .ported },
    .{ .file = "version.rs", .name = "version_long_flag_no_version", .status = .ported },
    .{ .file = "version.rs", .name = "version_short_flag_with_version", .status = .ported },
    .{ .file = "version.rs", .name = "version_long_flag_with_version", .status = .ported },
    .{ .file = "version.rs", .name = "version_short_flag_with_long_version", .status = .ported },
    .{ .file = "version.rs", .name = "version_long_flag_with_long_version", .status = .ported },
    .{ .file = "version.rs", .name = "version_short_flag_with_both", .status = .ported },
    .{ .file = "version.rs", .name = "version_long_flag_with_both", .status = .ported },
    .{ .file = "version.rs", .name = "help_short_flag_no_version", .status = .ported },
    .{ .file = "version.rs", .name = "help_long_flag_no_version", .status = .ported },
    .{ .file = "version.rs", .name = "help_short_flag_with_version", .status = .ported },
    .{ .file = "version.rs", .name = "help_long_flag_with_version", .status = .ported },
    .{ .file = "version.rs", .name = "help_short_flag_with_long_version", .status = .ported },
    .{ .file = "version.rs", .name = "help_long_flag_with_long_version", .status = .ported },
    .{ .file = "version.rs", .name = "help_short_flag_with_both", .status = .ported },
    .{ .file = "version.rs", .name = "help_long_flag_with_both", .status = .ported },
    .{ .file = "version.rs", .name = "no_propagation_by_default_long", .status = .ported },
    .{ .file = "version.rs", .name = "no_propagation_by_default_short", .status = .ported },
    .{ .file = "version.rs", .name = "propagate_version_long", .status = .ported },
    .{ .file = "version.rs", .name = "propagate_version_short", .status = .ported },
    .{ .file = "version.rs", .name = "override_version_long_with_user_flag", .status = .deferred, .note = "debug_assert (builder validation panic)" },
    .{ .file = "version.rs", .name = "override_version_short_with_user_flag", .status = .deferred, .note = "debug_assert (builder validation panic)" },
    .{ .file = "version.rs", .name = "version_required", .status = .deferred, .note = "debug_assert (ArgAction::Version without version)" },
    .{ .file = "version.rs", .name = "mut_arg_version_no_auto_version", .status = .deferred, .note = "mut_arg (mutate auto version flag)" },
    .{ .file = "version.rs", .name = "propagate_version_no_version_info", .status = .deferred, .note = "debug_assert (propagate without version)" },

    // ----- ignore_errors -----
    .{ .file = "ignore_errors.rs", .name = "single_short_arg_without_value", .status = .ported },
    .{ .file = "ignore_errors.rs", .name = "single_long_arg_without_value", .status = .ported },
    .{ .file = "ignore_errors.rs", .name = "multiple_args_and_final_arg_without_value", .status = .ported },
    .{ .file = "ignore_errors.rs", .name = "multiple_args_and_intermittent_arg_without_value", .status = .ported },
    .{ .file = "ignore_errors.rs", .name = "unexpected_argument", .status = .ported },
    .{ .file = "ignore_errors.rs", .name = "did_you_mean", .status = .ported },
    .{ .file = "ignore_errors.rs", .name = "subcommand", .status = .ported },
    .{ .file = "ignore_errors.rs", .name = "help_flag", .status = .ported },
    .{ .file = "ignore_errors.rs", .name = "help_flag_subcommand", .status = .ported },
    .{ .file = "ignore_errors.rs", .name = "version_flag", .status = .ported },

    // ----- utf8.rs (only valid-UTF8 cases portable; rest are OsString/non-UTF8) -----
    .{ .file = "utf8.rs", .name = "allow_validated_utf8_value_of", .status = .ported },
    .{ .file = "utf8.rs", .name = "allow_validated_utf8_external_subcommand_values_of", .status = .ported },
    .{ .file = "utf8.rs", .name = "invalid_utf8_strict_positional", .status = .deferred, .note = "UTF-8 strictness (Zig args are []const u8)" },
    .{ .file = "utf8.rs", .name = "invalid_utf8_strict_option_short_space", .status = .deferred, .note = "UTF-8 strictness" },
    .{ .file = "utf8.rs", .name = "invalid_utf8_strict_option_short_equals", .status = .deferred, .note = "UTF-8 strictness" },
    .{ .file = "utf8.rs", .name = "invalid_utf8_strict_option_short_no_space", .status = .deferred, .note = "UTF-8 strictness" },
    .{ .file = "utf8.rs", .name = "invalid_utf8_strict_option_long_space", .status = .deferred, .note = "UTF-8 strictness" },
    .{ .file = "utf8.rs", .name = "invalid_utf8_strict_option_long_equals", .status = .deferred, .note = "UTF-8 strictness" },
    .{ .file = "utf8.rs", .name = "invalid_utf8_strict_invalid_short", .status = .deferred, .note = "UTF-8 strictness" },
    .{ .file = "utf8.rs", .name = "invalid_utf8_strict_invalid_long", .status = .deferred, .note = "UTF-8 strictness" },
    .{ .file = "utf8.rs", .name = "invalid_utf8_positional", .status = .deferred, .note = "OsString (invalid UTF-8 values)" },
    .{ .file = "utf8.rs", .name = "invalid_utf8_option_short_space", .status = .deferred, .note = "OsString (invalid UTF-8 values)" },
    .{ .file = "utf8.rs", .name = "invalid_utf8_option_short_equals", .status = .deferred, .note = "OsString (invalid UTF-8 values)" },
    .{ .file = "utf8.rs", .name = "invalid_utf8_option_short_no_space", .status = .deferred, .note = "OsString (invalid UTF-8 values)" },
    .{ .file = "utf8.rs", .name = "invalid_utf8_option_long_space", .status = .deferred, .note = "OsString (invalid UTF-8 values)" },
    .{ .file = "utf8.rs", .name = "invalid_utf8_option_long_equals", .status = .deferred, .note = "OsString (invalid UTF-8 values)" },
    .{ .file = "utf8.rs", .name = "refuse_invalid_utf8_subcommand_with_allow_external_subcommands", .status = .deferred, .note = "OsString subcommand" },
    .{ .file = "utf8.rs", .name = "refuse_invalid_utf8_subcommand_when_args_are_allowed_with_allow_external_subcommands", .status = .deferred, .note = "OsString subcommand" },
    .{ .file = "utf8.rs", .name = "refuse_invalid_utf8_subcommand_args_with_allow_external_subcommands", .status = .deferred, .note = "OsString subcommand args" },
    .{ .file = "utf8.rs", .name = "allow_invalid_utf8_subcommand_args_with_allow_external_subcommands", .status = .deferred, .note = "OsString subcommand args" },
    .{ .file = "utf8.rs", .name = "panic_validated_utf8_external_subcommand_values_of_os", .status = .deferred, .note = "should_panic (OsString downcast)" },
    .{ .file = "utf8.rs", .name = "allow_invalid_utf8_external_subcommand_values_of_os", .status = .deferred, .note = "OsString values" },
    .{ .file = "utf8.rs", .name = "panic_invalid_utf8_external_subcommand_values_of", .status = .deferred, .note = "should_panic (String downcast)" },

    // ----- default_vals.rs (default_value / default_values / *_if conditionals) -----
    .{ .file = "default_vals.rs", .name = "opts", .status = .ported },
    .{ .file = "default_vals.rs", .name = "positionals", .status = .ported },
    .{ .file = "default_vals.rs", .name = "opt_user_override", .status = .ported },
    .{ .file = "default_vals.rs", .name = "positional_user_override", .status = .ported },
    .{ .file = "default_vals.rs", .name = "default_has_index", .status = .ported },
    .{ .file = "default_vals.rs", .name = "issue_1050_num_vals_and_defaults", .status = .ported },
    .{ .file = "default_vals.rs", .name = "conditional_reqs_pass", .status = .ported },
    .{ .file = "default_vals.rs", .name = "default_vals_donnot_show_in_smart_usage", .status = .ported },
    .{ .file = "default_vals.rs", .name = "required_args_with_default_values", .status = .ported },
    .{ .file = "default_vals.rs", .name = "required_groups_with_default_values", .status = .ported },
    .{ .file = "default_vals.rs", .name = "multiple_defaults", .status = .ported },
    .{ .file = "default_vals.rs", .name = "multiple_defaults_override", .status = .ported },
    .{ .file = "default_vals.rs", .name = "default_if_arg_present_no_arg_with_value_with_default_user_override", .status = .ported },
    .{ .file = "default_vals.rs", .name = "default_if_arg_present_no_arg_with_value_with_default_user_override_fail", .status = .ported },
    .{ .file = "default_vals.rs", .name = "default_if_arg_present_with_value_no_arg_with_default", .status = .ported },
    .{ .file = "default_vals.rs", .name = "default_if_arg_present_with_value_no_arg_with_default_fail", .status = .ported },
    .{ .file = "default_vals.rs", .name = "default_if_arg_present_with_value_no_default_user_override", .status = .ported },
    .{ .file = "default_vals.rs", .name = "default_if_arg_present_with_value_with_default", .status = .ported },
    .{ .file = "default_vals.rs", .name = "default_if_arg_present_with_value_with_default_user_override", .status = .ported },
    .{ .file = "default_vals.rs", .name = "default_ifs_arg_present_order", .status = .ported },
    .{ .file = "default_vals.rs", .name = "default_values_if_arg_present_no_arg_with_value_with_default_user_override", .status = .ported },
    .{ .file = "default_vals.rs", .name = "default_values_if_arg_present_no_arg_with_value_with_default_user_override_fail", .status = .ported },
    .{ .file = "default_vals.rs", .name = "default_values_if_arg_present_with_value_no_arg_with_default", .status = .ported },
    .{ .file = "default_vals.rs", .name = "default_values_if_arg_present_with_value_no_arg_with_default_fail", .status = .ported },
    .{ .file = "default_vals.rs", .name = "default_values_if_arg_present_with_value_no_default_fail", .status = .ported },
    .{ .file = "default_vals.rs", .name = "default_values_if_arg_present_with_value_no_default_user_override", .status = .ported },
    .{ .file = "default_vals.rs", .name = "default_values_if_arg_present_with_value_with_default", .status = .ported },
    .{ .file = "default_vals.rs", .name = "default_values_if_arg_present_with_value_with_default_user_override", .status = .ported },
    .{ .file = "default_vals.rs", .name = "default_values_ifs_arg_present_order", .status = .ported },
    .{ .file = "default_vals.rs", .name = "osstr_opts", .status = .deferred, .note = "OsStr" },
    .{ .file = "default_vals.rs", .name = "osstr_opt_user_override", .status = .deferred, .note = "OsStr" },
    .{ .file = "default_vals.rs", .name = "osstr_positionals", .status = .deferred, .note = "OsStr" },
    .{ .file = "default_vals.rs", .name = "osstr_positional_user_override", .status = .deferred, .note = "OsStr" },
    .{ .file = "default_vals.rs", .name = "default_value_ifs_os", .status = .deferred, .note = "OsStr" },
    .{ .file = "default_vals.rs", .name = "default_values_ifs_os", .status = .deferred, .note = "OsStr" },
    .{ .file = "default_vals.rs", .name = "valid_delimited_default_values", .status = .deferred, .note = "debug_assert" },
    .{ .file = "default_vals.rs", .name = "opt_without_value_fail", .status = .deferred, .note = "NonEmptyStringValueParser" },
    .{ .file = "default_vals.rs", .name = "default_independent_of_trailing", .status = .deferred, .note = "dont_delimit_trailing_values" },
    .{ .file = "default_vals.rs", .name = "missing_with_value_delimiter", .status = .deferred, .note = "default_missing_values (plural) + delimiter" },

    // ----- opts.rs (empty values, =-prefixed values, require_equals, leading hyphen) -----
    .{ .file = "opts.rs", .name = "issue_1105_empty_value_long_equals", .status = .ported },
    .{ .file = "opts.rs", .name = "issue_1105_empty_value_long_explicit", .status = .ported },
    .{ .file = "opts.rs", .name = "issue_1105_empty_value_long_fail", .status = .ported },
    .{ .file = "opts.rs", .name = "issue_1105_empty_value_short_equals", .status = .ported },
    .{ .file = "opts.rs", .name = "issue_1105_empty_value_short_explicit", .status = .ported },
    .{ .file = "opts.rs", .name = "issue_1105_empty_value_short_explicit_no_space", .status = .ported },
    .{ .file = "opts.rs", .name = "issue_1105_empty_value_short_fail", .status = .ported },
    .{ .file = "opts.rs", .name = "long_eq_val_starts_with_eq", .status = .ported },
    .{ .file = "opts.rs", .name = "short_eq_val_starts_with_eq", .status = .ported },
    .{ .file = "opts.rs", .name = "require_equals_min_values_zero", .status = .ported },
    .{ .file = "opts.rs", .name = "issue_1047_min_zero_vals_default_val", .status = .ported },
    .{ .file = "opts.rs", .name = "leading_hyphen_with_flag_after", .status = .ported },
    .{ .file = "opts.rs", .name = "leading_hyphen_with_flag_before", .status = .ported },
    .{ .file = "opts.rs", .name = "leading_hyphen_with_only_pos_follows", .status = .ported },
    .{ .file = "opts.rs", .name = "issue_2022_get_flags_misuse", .status = .ported },
    .{ .file = "opts.rs", .name = "issue_2279", .status = .ported },
    .{ .file = "opts.rs", .name = "leading_hyphen_fail", .status = .deferred, .note = "error-kind ordering (-2 → UnknownArgument before missing-value)" },
    .{ .file = "opts.rs", .name = "short_non_ascii_no_space", .status = .deferred, .note = "non-ASCII short flag (short_char is u8)" },

    // ----- groups.rs (ArgGroup) -----
    .{ .file = "groups.rs", .name = "required_group_missing_arg", .status = .ported },
    .{ .file = "groups.rs", .name = "group_single_value", .status = .ported },
    .{ .file = "groups.rs", .name = "group_empty", .status = .ported },
    .{ .file = "groups.rs", .name = "group_required_flags_empty", .status = .ported },
    .{ .file = "groups.rs", .name = "group_multi_value_single_arg", .status = .ported },
    .{ .file = "groups.rs", .name = "empty_group", .status = .ported },
    .{ .file = "groups.rs", .name = "req_group_usage_string", .status = .ported },
    .{ .file = "groups.rs", .name = "req_group_with_conflict_usage_string", .status = .ported },
    .{ .file = "groups.rs", .name = "req_group_with_conflict_usage_string_only_options", .status = .ported },
    .{ .file = "groups.rs", .name = "required_group_multiple_args", .status = .ported },
    .{ .file = "groups.rs", .name = "group_multiple_args_error", .status = .ported },
    .{ .file = "groups.rs", .name = "group_overrides_required", .status = .ported },
    .{ .file = "groups.rs", .name = "group_usage_use_val_name", .status = .ported },
    .{ .file = "groups.rs", .name = "group_acts_like_arg", .status = .ported },
    .{ .file = "groups.rs", .name = "non_existing_arg", .status = .deferred, .note = "debug_assert" },
    .{ .file = "groups.rs", .name = "unique_group_name", .status = .deferred, .note = "debug_assert" },
    .{ .file = "groups.rs", .name = "groups_new_of_arg_name", .status = .deferred, .note = "debug_assert" },
    .{ .file = "groups.rs", .name = "arg_group_new_of_arg_name", .status = .deferred, .note = "debug_assert" },
    .{ .file = "groups.rs", .name = "conflict_with_group", .status = .deferred, .note = "conflicts_with(group) subject/ordering in error" },
    .{ .file = "groups.rs", .name = "conflict_with_overlapping_group_in_error", .status = .deferred, .note = "arg in multiple groups" },
    .{ .file = "groups.rs", .name = "requires_group_with_overlapping_group_in_error", .status = .deferred, .note = "arg in multiple groups" },
    .{ .file = "groups.rs", .name = "issue_1794", .status = .deferred, .note = "commented out in clap (known-broken)" },

    // ----- grouped occurrences (get_occurrences) -----
    .{ .file = "occurrences.rs", .name = "grouped_value_works", .status = .ported },
    .{ .file = "occurrences.rs", .name = "issue_1026", .status = .ported },
    .{ .file = "occurrences.rs", .name = "grouped_value_long_flag_delimiter", .status = .ported },
    .{ .file = "occurrences.rs", .name = "grouped_value_short_flag_delimiter", .status = .ported },
    .{ .file = "occurrences.rs", .name = "grouped_value_positional_arg", .status = .ported },
    .{ .file = "occurrences.rs", .name = "grouped_value_multiple_positional_arg", .status = .ported },
    .{ .file = "occurrences.rs", .name = "grouped_value_multiple_positional_arg_last_multiple", .status = .ported },
    .{ .file = "occurrences.rs", .name = "grouped_interleaved_positional_values", .status = .ported },
    .{ .file = "occurrences.rs", .name = "grouped_interleaved_positional_occurrences", .status = .ported },
    .{ .file = "occurrences.rs", .name = "issue_2171", .status = .deferred, .note = "args_override_self short-cluster repeat (no get_occurrences)" },

    // ----- help.rs: subcommand help dispatch -----
    .{ .file = "help.rs", .name = "subcommand_short_help", .status = .ported },
    .{ .file = "help.rs", .name = "subcommand_long_help", .status = .ported },
    .{ .file = "help.rs", .name = "subcommand_help_rev", .status = .ported },
    .{ .file = "help.rs", .name = "multi_level_sc_help", .status = .ported },
    .{ .file = "help.rs", .name = "subcmd_help_subcmd_help", .status = .deferred, .note = "`help help` synthetic help-subcommand target" },
    .{ .file = "help.rs", .name = "help_subcmd_help", .status = .deferred, .note = "`help help` synthetic help-subcommand target" },

    // ----- help.rs: dotted positionals, last usage, default/hidden in help -----
    .{ .file = "help.rs", .name = "positional_multiple_values_is_dotted", .status = .ported },
    .{ .file = "help.rs", .name = "positional_multiple_occurrences_is_dotted", .status = .ported },
    .{ .file = "help.rs", .name = "args_with_last_usage", .status = .ported },
    .{ .file = "help.rs", .name = "empty_default_value", .status = .ported },
    .{ .file = "help.rs", .name = "hide_args", .status = .ported },
    .{ .file = "help.rs", .name = "too_few_value_names_is_dotted", .status = .deferred, .note = "`...` when num_args > value_names count" },
    .{ .file = "help.rs", .name = "hide_default_val", .status = .deferred, .note = "hide_default_value" },
    .{ .file = "help.rs", .name = "hide_possible_vals", .status = .deferred, .note = "hide_possible_values" },
    .{ .file = "help.rs", .name = "possible_vals_with_help", .status = .deferred, .note = "PossibleValue.hide + per-value help block" },
    .{ .file = "help.rs", .name = "help_enum_arg_with_no_description", .status = .deferred, .note = "long possible-values block + hide + default" },
    .{ .file = "help.rs", .name = "display_name_default", .status = .deferred, .note = "get_display_name reflection" },
    .{ .file = "help.rs", .name = "display_name_explicit", .status = .deferred, .note = "display_name setter + reflection" },
    .{ .file = "help.rs", .name = "help_without_short", .status = .deferred, .note = "get_short reflection" },

    // ----- help.rs: custom help headings -----
    .{ .file = "help.rs", .name = "mixed_argument_types", .status = .ported },
    .{ .file = "help.rs", .name = "mixed_argument_types_no_short", .status = .ported },
    .{ .file = "help.rs", .name = "only_custom_heading_pos_no_args", .status = .ported },
    .{ .file = "help.rs", .name = "multiple_custom_help_headers", .status = .ported },
    .{ .file = "help.rs", .name = "mixed_argument_types_short_positional", .status = .deferred, .note = "short on positional (debug_assert)" },

    // ----- help.rs: help_expected (debug_assert build validation) -----
    .{ .file = "help.rs", .name = "help_required_and_given", .status = .deferred, .note = "help_expected (debug_assert)" },
    .{ .file = "help.rs", .name = "help_required_and_no_args", .status = .deferred, .note = "help_expected (debug_assert)" },
    .{ .file = "help.rs", .name = "help_required_but_not_given", .status = .deferred, .note = "help_expected (debug_assert)" },
    .{ .file = "help.rs", .name = "help_required_but_not_given_for_one_of_two_arguments", .status = .deferred, .note = "help_expected (debug_assert)" },
    .{ .file = "help.rs", .name = "help_required_but_not_given_settings_after_args", .status = .deferred, .note = "help_expected (debug_assert)" },
    .{ .file = "help.rs", .name = "help_required_globally", .status = .deferred, .note = "help_expected (debug_assert)" },
    .{ .file = "help.rs", .name = "help_required_globally_but_not_given_for_subcommand", .status = .deferred, .note = "help_expected (debug_assert)" },
    .{ .file = "help.rs", .name = "help_required_and_given_for_subcommand", .status = .deferred, .note = "help_expected (debug_assert)" },

    // ----- help.rs: global args in help / next_line_help -----
    .{ .file = "help.rs", .name = "global_args_should_show_on_toplevel_help_message", .status = .ported },
    .{ .file = "help.rs", .name = "global_args_should_show_on_help_message_for_subcommand", .status = .ported },
    .{ .file = "help.rs", .name = "global_args_should_show_on_help_message_for_nested_subcommand", .status = .ported },
    .{ .file = "help.rs", .name = "global_args_should_not_show_on_help_message_for_help_help", .status = .deferred, .note = "help target = synthetic help subcommand" },
    .{ .file = "help.rs", .name = "next_line_arg_short", .status = .deferred, .note = "next_line_help long-mode commands no-blank nuance" },
    .{ .file = "help.rs", .name = "next_line_command_short", .status = .deferred, .note = "next_line_help long-mode commands no-blank nuance" },
    .{ .file = "help.rs", .name = "next_line_arg_wrapped", .status = .deferred, .note = "next_line_help + multi-paragraph wrap" },
    .{ .file = "help.rs", .name = "next_line_command_wrapped", .status = .deferred, .note = "next_line_help + multi-paragraph wrap" },

    // ----- help.rs: flatten_help -----
    .{ .file = "help.rs", .name = "flatten_basic", .status = .ported },
    .{ .file = "help.rs", .name = "flatten_without_subcommands", .status = .ported },
    .{ .file = "help.rs", .name = "flatten_with_subcommand_required", .status = .ported },
    .{ .file = "help.rs", .name = "flatten_with_global", .status = .ported },
    .{ .file = "help.rs", .name = "flatten_with_external_subcommand", .status = .ported },
    .{ .file = "help.rs", .name = "flatten_with_args_conflicts_with_subcommands", .status = .ported },
    .{ .file = "help.rs", .name = "flatten_not_recursive", .status = .ported },
    .{ .file = "help.rs", .name = "flatten_arg_required", .status = .deferred, .note = "parent required args in subcommand usage lines" },
    .{ .file = "help.rs", .name = "flatten_recursive", .status = .deferred, .note = "recursive flatten" },
    .{ .file = "help.rs", .name = "flatten_hidden_command", .status = .deferred, .note = "hidden subcommand in flatten" },
    .{ .file = "help.rs", .name = "flatten_single_hidden_command", .status = .deferred, .note = "hidden subcommand in flatten" },
    .{ .file = "help.rs", .name = "flatten_help_cmd", .status = .deferred, .note = "long layout under flatten" },
    .{ .file = "help.rs", .name = "flatten_long_help", .status = .deferred, .note = "long layout under flatten" },
    .{ .file = "help.rs", .name = "flatten_short_help", .status = .deferred, .note = "long layout under flatten" },

    // ----- help.rs: try-help hint logic -----
    .{ .file = "help.rs", .name = "try_help_default", .status = .ported },
    .{ .file = "help.rs", .name = "try_help_custom_flag", .status = .ported },
    .{ .file = "help.rs", .name = "try_help_custom_flag_short", .status = .ported },
    .{ .file = "help.rs", .name = "try_help_custom_flag_long", .status = .ported },
    .{ .file = "help.rs", .name = "try_help_custom_flag_no_action", .status = .ported },
    .{ .file = "help.rs", .name = "try_help_subcommand_default", .status = .ported },
    .{ .file = "help.rs", .name = "try_help_subcommand_custom_flag", .status = .ported },
    .{ .file = "help.rs", .name = "try_help_subcommand_custom_flag_no_action", .status = .ported },

    // ----- subcommands.rs (dispatch, same-name args, -- + subcommand-like value) -----
    .{ .file = "subcommands.rs", .name = "subcommand", .status = .ported },
    .{ .file = "subcommands.rs", .name = "subcommand_multiple", .status = .ported },
    .{ .file = "subcommands.rs", .name = "subcommand_none_given", .status = .ported },
    .{ .file = "subcommands.rs", .name = "subcommand_not_recognized", .status = .ported },
    .{ .file = "subcommands.rs", .name = "subcommand_after_argument", .status = .ported },
    .{ .file = "subcommands.rs", .name = "subcommand_after_argument_looks_like_help", .status = .ported },
    .{ .file = "subcommands.rs", .name = "issue_2494_subcommand_is_present", .status = .ported },
    .{ .file = "subcommands.rs", .name = "issue_1031_args_with_same_name", .status = .ported },
    .{ .file = "subcommands.rs", .name = "issue_1031_args_with_same_name_no_more_vals", .status = .ported },
    .{ .file = "subcommands.rs", .name = "issue_1722_not_emit_error_when_arg_follows_similar_to_a_subcommand", .status = .ported },
    .{ .file = "subcommands.rs", .name = "issue_1161_multiple_hyphen_hyphen", .status = .ported },
    .{ .file = "subcommands.rs", .name = "subcommand_used_after_double_dash", .status = .deferred, .note = "'-- subcommand' tip (remove the --)" },
    .{ .file = "subcommands.rs", .name = "duplicate_subcommand", .status = .deferred, .note = "debug_assert" },
    .{ .file = "subcommands.rs", .name = "duplicate_subcommand_alias", .status = .deferred, .note = "debug_assert" },

    // ----- multicall -----
    .{ .file = "subcommands.rs", .name = "busybox_like_multicall", .status = .ported },
    .{ .file = "subcommands.rs", .name = "hostname_like_multicall", .status = .ported },
    .{ .file = "subcommands.rs", .name = "bad_multicall_command_error", .status = .ported },
    .{ .file = "subcommands.rs", .name = "multicall_help_flag", .status = .ported },
    .{ .file = "subcommands.rs", .name = "multicall_help_subcommand", .status = .ported },
    .{ .file = "subcommands.rs", .name = "cant_have_args_with_multicall", .status = .deferred, .note = "debug_assert (build-time panic)" },
    .{ .file = "subcommands.rs", .name = "multicall_render_help", .status = .deferred, .note = "find_subcommand_mut + render_help API" },

    // ----- subcommand value-name / help-heading settings -----
    .{ .file = "subcommands.rs", .name = "subcommand_placeholder_test", .status = .ported },

    // ----- trailing_var_arg -----
    .{ .file = "app_settings.rs", .name = "trailing_var_arg_with_hyphen_values_escape_first", .status = .ported },
    .{ .file = "app_settings.rs", .name = "trailing_var_arg_with_hyphen_values_escape_middle", .status = .ported },
    .{ .file = "app_settings.rs", .name = "trailing_var_arg_with_hyphen_values_short_first", .status = .ported },
    .{ .file = "app_settings.rs", .name = "trailing_var_arg_with_hyphen_values_short_middle", .status = .ported },
    .{ .file = "app_settings.rs", .name = "trailing_var_arg_with_hyphen_values_long_first", .status = .ported },
    .{ .file = "app_settings.rs", .name = "trailing_var_arg_with_hyphen_values_long_middle", .status = .ported },
    .{ .file = "app_settings.rs", .name = "dont_delim_values_trailingvararg", .status = .deferred, .note = "value_delimiter + trailing_var_arg interaction" },
    .{ .file = "app_settings.rs", .name = "delim_values_trailingvararg", .status = .deferred, .note = "value_delimiter + trailing_var_arg interaction" },
    .{ .file = "app_settings.rs", .name = "delim_values_trailingvararg_with_delim", .status = .deferred, .note = "value_delimiter + trailing_var_arg interaction" },

    // ----- did-you-mean suggestions -----
    .{ .file = "opts.rs", .name = "did_you_mean", .status = .ported },
    .{ .file = "opts.rs", .name = "issue_1073_suboptimal_flag_suggestion", .status = .ported },
    .{ .file = "subcommands.rs", .name = "subcmd_did_you_mean_output", .status = .ported },
    .{ .file = "subcommands.rs", .name = "subcmd_did_you_mean_output_ambiguous", .status = .ported },
    .{ .file = "subcommands.rs", .name = "subcmd_did_you_mean_output_arg", .status = .deferred, .note = "flag→subcommand-arg cross suggestion" },
    .{ .file = "subcommands.rs", .name = "subcmd_did_you_mean_output_arg_false_positives", .status = .deferred, .note = "flag→subcommand-arg cross suggestion" },

    // ----- infer_subcommands / infer_long_args -----
    .{ .file = "app_settings.rs", .name = "infer_subcommands_fail_no_args", .status = .ported },
    .{ .file = "app_settings.rs", .name = "infer_subcommands_fail_with_args", .status = .ported },
    .{ .file = "app_settings.rs", .name = "infer_subcommands_fail_with_args2", .status = .ported },
    .{ .file = "app_settings.rs", .name = "infer_subcommands_pass", .status = .ported },
    .{ .file = "app_settings.rs", .name = "infer_subcommands_pass_close", .status = .ported },
    .{ .file = "app_settings.rs", .name = "infer_subcommands_pass_exact_match", .status = .ported },
    .{ .file = "app_settings.rs", .name = "infer_subcommands_pass_conflicting_aliases", .status = .ported },
    .{ .file = "app_settings.rs", .name = "infer_long_flag_pass_conflicting_aliases", .status = .ported },
    .{ .file = "app_settings.rs", .name = "infer_long_flag", .status = .ported },
    .{ .file = "app_settings.rs", .name = "infer_subcommands_long_flag_fail_with_args2", .status = .ported },
    .{ .file = "app_settings.rs", .name = "infer_subcommands_fail_suggestions", .status = .ported },
    .{ .file = "opts.rs", .name = "infer_long_arg_pass", .status = .ported },
    .{ .file = "opts.rs", .name = "infer_long_arg_pass_conflicts_exact_match", .status = .ported },
    .{ .file = "opts.rs", .name = "infer_long_arg_pass_conflicting_aliases", .status = .ported },
    .{ .file = "opts.rs", .name = "infer_long_arg_fail_conflicts", .status = .ported },

    // ----- allow_hyphen_values / allow_negative_numbers -----
    .{ .file = "app_settings.rs", .name = "leading_hyphen_short", .status = .ported },
    .{ .file = "app_settings.rs", .name = "leading_hyphen_long", .status = .ported },
    .{ .file = "app_settings.rs", .name = "leading_hyphen_opt", .status = .ported },
    .{ .file = "app_settings.rs", .name = "allow_negative_numbers_success", .status = .ported },
    .{ .file = "app_settings.rs", .name = "allow_negative_numbers_fail", .status = .ported },
    .{ .file = "opts.rs", .name = "leading_hyphen_pass", .status = .ported },
    .{ .file = "positionals.rs", .name = "issue_946", .status = .ported },
    .{ .file = "app_settings.rs", .name = "issue_1437_allow_hyphen_values_for_positional_arg", .status = .deferred, .note = "exact fixture untested (simplified variant ported)" },

    // ----- env.rs (Arg.env fallback via injected EnvSource) -----
    .{ .file = "env.rs", .name = "env", .status = .ported },
    .{ .file = "env.rs", .name = "no_env", .status = .ported },
    .{ .file = "env.rs", .name = "no_env_no_takes_value", .status = .deferred, .note = "env flag (no takes_value)" },
    .{ .file = "env.rs", .name = "with_default", .status = .ported },
    .{ .file = "env.rs", .name = "opt_user_override", .status = .ported },
    .{ .file = "env.rs", .name = "multiple_one", .status = .ported },
    .{ .file = "env.rs", .name = "multiple_three", .status = .ported },
    .{ .file = "env.rs", .name = "multiple_no_delimiter", .status = .ported },
    .{ .file = "env.rs", .name = "possible_value", .status = .ported },
    .{ .file = "env.rs", .name = "not_possible_value", .status = .ported },
    .{ .file = "env.rs", .name = "env_bool_literal", .status = .deferred, .note = "FalseyValueParser" },
    .{ .file = "env.rs", .name = "env_os", .status = .deferred, .note = "OsStr env" },
    .{ .file = "env.rs", .name = "positionals", .status = .deferred, .note = "env positional (untested here)" },
    .{ .file = "env.rs", .name = "positionals_user_override", .status = .deferred, .note = "env positional (untested here)" },
    .{ .file = "env.rs", .name = "value_parser", .status = .deferred, .note = "closure value_parser" },
    .{ .file = "env.rs", .name = "value_parser_output", .status = .deferred, .note = "value_parser!(i32) on env" },
    .{ .file = "env.rs", .name = "value_parser_invalid", .status = .deferred, .note = "closure value_parser" },

    // ----- flag_subcommands.rs (short_flag / long_flag subcommands) -----
    .{ .file = "flag_subcommands.rs", .name = "flag_subcommand_normal", .status = .ported },
    .{ .file = "flag_subcommands.rs", .name = "flag_subcommand_short", .status = .ported },
    .{ .file = "flag_subcommands.rs", .name = "flag_subcommand_short_with_args", .status = .ported },
    .{ .file = "flag_subcommands.rs", .name = "flag_subcommand_short_with_alias", .status = .ported },
    .{ .file = "flag_subcommands.rs", .name = "flag_subcommand_long", .status = .ported },
    .{ .file = "flag_subcommands.rs", .name = "flag_subcommand_long_with_aliases", .status = .ported },
    .{ .file = "flag_subcommands.rs", .name = "flag_subcommand_short_after_long_arg", .status = .ported },
    .{ .file = "flag_subcommands.rs", .name = "flag_subcommand_multiple", .status = .ported },
    .{ .file = "flag_subcommands.rs", .name = "flag_subcommand_long_short_normal_usage_string", .status = .ported },
    .{ .file = "flag_subcommands.rs", .name = "flag_subcommand_long_normal_usage_string", .status = .ported },
    .{ .file = "flag_subcommands.rs", .name = "flag_subcommand_short_normal_usage_string", .status = .ported },
    .{ .file = "flag_subcommands.rs", .name = "flag_subcommand_normal_with_alias", .status = .deferred, .note = "name-alias invocation (untested here)" },
    .{ .file = "flag_subcommands.rs", .name = "flag_subcommand_long_with_alias", .status = .deferred, .note = "single long-flag alias (untested here)" },
    .{ .file = "flag_subcommands.rs", .name = "flag_subcommand_short_with_aliases", .status = .deferred, .note = "covered by short_with_alias" },
    .{ .file = "flag_subcommands.rs", .name = "flag_subcommand_normal_with_alias_vis_and_hidden", .status = .deferred, .note = "flag aliases in help listing" },
    .{ .file = "flag_subcommands.rs", .name = "flag_subcommand_short_with_aliases_vis_and_hidden", .status = .deferred, .note = "flag aliases in help listing" },
    .{ .file = "flag_subcommands.rs", .name = "flag_subcommand_long_with_aliases_vis_and_hidden", .status = .deferred, .note = "flag aliases in help listing" },
    .{ .file = "flag_subcommands.rs", .name = "flag_subcommand_short_with_alias_hyphen", .status = .deferred, .note = "hyphen short-flag alias" },
    .{ .file = "flag_subcommands.rs", .name = "flag_subcommand_short_with_aliases_hyphen", .status = .deferred, .note = "hyphen short-flag alias" },
    .{ .file = "flag_subcommands.rs", .name = "flag_subcommand_short_with_alias_same_as_short_flag", .status = .deferred, .note = "debug_assert" },
    .{ .file = "flag_subcommands.rs", .name = "flag_subcommand_long_with_alias_same_as_long_flag", .status = .deferred, .note = "debug_assert" },
    .{ .file = "flag_subcommands.rs", .name = "flag_subcommand_short_conflict_with_arg", .status = .deferred, .note = "debug_assert" },
    .{ .file = "flag_subcommands.rs", .name = "flag_subcommand_short_conflict_with_alias", .status = .deferred, .note = "debug_assert" },
    .{ .file = "flag_subcommands.rs", .name = "flag_subcommand_long_conflict_with_alias", .status = .deferred, .note = "debug_assert" },
    .{ .file = "flag_subcommands.rs", .name = "flag_subcommand_short_conflict_with_arg_alias", .status = .deferred, .note = "debug_assert" },
    .{ .file = "flag_subcommands.rs", .name = "flag_subcommand_long_conflict_with_arg_alias", .status = .deferred, .note = "debug_assert" },
    .{ .file = "flag_subcommands.rs", .name = "flag_subcommand_long_conflict_with_arg", .status = .deferred, .note = "debug_assert" },
    .{ .file = "flag_subcommands.rs", .name = "flag_subcommand_conflict_with_help", .status = .deferred, .note = "debug_assert" },
    .{ .file = "flag_subcommands.rs", .name = "flag_subcommand_conflict_with_version", .status = .deferred, .note = "debug_assert" },
    .{ .file = "flag_subcommands.rs", .name = "flag_subcommand_long_infer_pass", .status = .ported },
    .{ .file = "flag_subcommands.rs", .name = "flag_subcommand_long_infer_fail", .status = .ported },
    .{ .file = "flag_subcommands.rs", .name = "flag_subcommand_long_infer_pass_close", .status = .ported },
    .{ .file = "flag_subcommands.rs", .name = "flag_subcommand_long_infer_exact_match", .status = .ported },

    // ----- app_settings.rs (colour) -----
    .{ .file = "app_settings.rs", .name = "color_is_global", .status = .ported },

    // ----- derive_order.rs / display_order.rs (display_order / next_display_order) -----
    .{ .file = "derive_order.rs", .name = "no_derive_order", .status = .ported },
    .{ .file = "derive_order.rs", .name = "derive_order", .status = .ported },
    .{ .file = "derive_order.rs", .name = "derive_order_next_order", .status = .ported },
    .{ .file = "derive_order.rs", .name = "derive_order_no_next_order", .status = .ported },
    .{ .file = "display_order.rs", .name = "very_large_display_order", .status = .ported },

    // ----- hidden_args.rs (hide on args / positionals / subcommands) -----
    .{ .file = "hidden_args.rs", .name = "hide_args", .status = .ported },
    .{ .file = "hidden_args.rs", .name = "hide_pos_args", .status = .ported },
    .{ .file = "hidden_args.rs", .name = "hide_subcmds", .status = .ported },
    .{ .file = "hidden_args.rs", .name = "hide_opt_args_only", .status = .ported },
    .{ .file = "hidden_args.rs", .name = "hide_pos_args_only", .status = .ported },
    .{ .file = "hidden_args.rs", .name = "hide_subcmds_only", .status = .ported },
    .{ .file = "hidden_args.rs", .name = "hidden_arg_with_possible_value_with_help", .status = .ported },
    .{ .file = "hidden_args.rs", .name = "hide_short_args", .status = .ported },
    .{ .file = "hidden_args.rs", .name = "hide_short_args_long_help", .status = .ported },
    .{ .file = "hidden_args.rs", .name = "hide_long_args", .status = .ported },
    .{ .file = "hidden_args.rs", .name = "hide_long_args_short_help", .status = .ported },

    // ----- arg_aliases.rs / arg_aliases_short.rs (arg long/short aliases) -----
    .{ .file = "arg_aliases.rs", .name = "single_alias_of_option", .status = .ported },
    .{ .file = "arg_aliases.rs", .name = "multiple_aliases_of_option", .status = .ported },
    .{ .file = "arg_aliases.rs", .name = "single_alias_of_flag", .status = .ported },
    .{ .file = "arg_aliases.rs", .name = "multiple_aliases_of_flag", .status = .ported },
    .{ .file = "arg_aliases.rs", .name = "alias_on_a_subcommand_option", .status = .ported },
    .{ .file = "arg_aliases.rs", .name = "invisible_arg_aliases_help_output", .status = .ported },
    .{ .file = "arg_aliases.rs", .name = "visible_arg_aliases_help_output", .status = .ported },
    .{ .file = "arg_aliases.rs", .name = "get_aliases", .status = .deferred, .note = "get_*_aliases reflection API" },
    .{ .file = "arg_aliases_short.rs", .name = "single_short_alias_of_option", .status = .ported },
    .{ .file = "arg_aliases_short.rs", .name = "multiple_short_aliases_of_option", .status = .ported },
    .{ .file = "arg_aliases_short.rs", .name = "single_short_alias_of_flag", .status = .ported },
    .{ .file = "arg_aliases_short.rs", .name = "visible_short_arg_aliases_help_output", .status = .deferred, .note = "non-ASCII short alias (char vs u8)" },
    // subcommand aliases (subcommands.rs)
    .{ .file = "subcommands.rs", .name = "single_alias", .status = .ported },
    .{ .file = "subcommands.rs", .name = "multiple_aliases", .status = .ported },
    .{ .file = "subcommands.rs", .name = "alias_help", .status = .ported },
    .{ .file = "subcommands.rs", .name = "visible_aliases_help_output", .status = .ported },
    .{ .file = "subcommands.rs", .name = "invisible_aliases_help_output", .status = .ported },

    // ----- delimiters.rs (value_delimiter) -----
    .{ .file = "delimiters.rs", .name = "opt_default_no_delim", .status = .ported },
    .{ .file = "delimiters.rs", .name = "opt_eq_no_delim", .status = .ported },
    .{ .file = "delimiters.rs", .name = "opt_s_eq_no_delim", .status = .ported },
    .{ .file = "delimiters.rs", .name = "opt_s_default_no_delim", .status = .ported },
    .{ .file = "delimiters.rs", .name = "opt_s_no_space_no_delim", .status = .ported },
    .{ .file = "delimiters.rs", .name = "opt_s_no_space_mult_no_delim", .status = .ported },
    .{ .file = "delimiters.rs", .name = "opt_eq_mult_def_delim", .status = .ported },
    // default_vals.rs delimited default
    .{ .file = "default_vals.rs", .name = "with_value_delimiter", .status = .ported },

    // ----- help.rs (before/after help + long_about; templates/wrapping/headings pending) -----
    .{ .file = "help.rs", .name = "after_and_before_help_output", .status = .ported },
    .{ .file = "help.rs", .name = "after_and_before_long_help_output", .status = .ported },
    .{ .file = "help.rs", .name = "long_about", .status = .ported },
    .{ .file = "help.rs", .name = "show_long_about_issue_897", .status = .ported },
    .{ .file = "help.rs", .name = "show_short_about_issue_897", .status = .ported },
    .{ .file = "help.rs", .name = "prefer_about_over_long_about_in_subcommands_list", .status = .ported },
    .{ .file = "help.rs", .name = "after_help_no_args", .status = .ported },
    .{ .file = "help.rs", .name = "issue_1642_long_help_spacing", .status = .ported },
    .{ .file = "help.rs", .name = "short_with_value", .status = .ported },
    .{ .file = "help.rs", .name = "short_with_count", .status = .ported },
    .{ .file = "help.rs", .name = "custom_heading_pos", .status = .ported },
    .{ .file = "help.rs", .name = "only_custom_heading_opts_no_args", .status = .ported },
    .{ .file = "help.rs", .name = "ripgrep_usage_using_templates", .status = .ported },
    .{ .file = "help.rs", .name = "dont_strip_padding_issue_5083", .status = .ported },
    .{ .file = "help.rs", .name = "no_wrap_default_help", .status = .ported },
    .{ .file = "help.rs", .name = "wrapped_help", .status = .ported },
    .{ .file = "help.rs", .name = "unwrapped_help", .status = .ported },
    .{ .file = "help.rs", .name = "final_word_wrapping", .status = .ported },
    .{ .file = "help.rs", .name = "wrapping_newline_chars", .status = .ported },
    .{ .file = "help.rs", .name = "wrapped_indentation", .status = .ported },
    .{ .file = "help.rs", .name = "possible_value_wrapped_help", .status = .deferred, .note = "long-help possible-value wrapping" },
    .{ .file = "help.rs", .name = "custom_headers_headers", .status = .ported },
    .{ .file = "help.rs", .name = "custom_help_headers_hide_args", .status = .ported },
    .{ .file = "help.rs", .name = "explicit_short_long_help", .status = .ported },

    // ----- default_vals.rs (default_value_if / default_values_if / *_ifs) -----
    .{ .file = "default_vals.rs", .name = "default_if_arg_present_no_default", .status = .ported },
    .{ .file = "default_vals.rs", .name = "default_if_arg_present_no_default_user_override", .status = .ported },
    .{ .file = "default_vals.rs", .name = "default_if_arg_present_no_arg_with_default", .status = .ported },
    .{ .file = "default_vals.rs", .name = "default_if_arg_present_with_default", .status = .ported },
    .{ .file = "default_vals.rs", .name = "default_if_arg_present_with_default_user_override", .status = .ported },
    .{ .file = "default_vals.rs", .name = "default_if_arg_present_no_arg_with_default_user_override", .status = .ported },
    .{ .file = "default_vals.rs", .name = "default_if_arg_present_with_value_no_default", .status = .ported },
    .{ .file = "default_vals.rs", .name = "default_values_if_arg_present_with_value_no_default", .status = .ported },
    .{ .file = "default_vals.rs", .name = "default_if_arg_present_with_value_no_default_fail", .status = .ported },
    .{ .file = "default_vals.rs", .name = "no_default_if_arg_present_with_value_no_default", .status = .ported },
    .{ .file = "default_vals.rs", .name = "no_default_if_arg_present_with_value_with_default", .status = .ported },
    .{ .file = "default_vals.rs", .name = "no_default_if_arg_present_with_value_with_default_user_override", .status = .ported },
    .{ .file = "default_vals.rs", .name = "no_default_if_arg_present_no_arg_with_value_with_default", .status = .ported },
    .{ .file = "default_vals.rs", .name = "default_ifs_arg_present", .status = .ported },
    .{ .file = "default_vals.rs", .name = "no_default_ifs_arg_present", .status = .ported },
    .{ .file = "default_vals.rs", .name = "default_ifs_arg_present_user_override", .status = .ported },
    .{ .file = "default_vals.rs", .name = "default_values_ifs_arg_present", .status = .ported },
    // deferred: regular plural `default_values` fallthrough (we have single default_value only)
    .{ .file = "default_vals.rs", .name = "no_default_values_if_arg_present_no_arg_with_value_with_default", .status = .deferred, .note = "default_values (plural)" },
    .{ .file = "default_vals.rs", .name = "no_default_values_if_arg_present_with_value_with_default_user_override", .status = .deferred, .note = "default_values (plural)" },
    .{ .file = "default_vals.rs", .name = "default_values_ifs_arg_present_user_override", .status = .deferred, .note = "default_values (plural)" },

    // ----- opts.rs -----
    .{ .file = "opts.rs", .name = "require_equals_fail", .status = .ported },
    .{ .file = "opts.rs", .name = "require_equals_fail_message", .status = .ported },
    .{ .file = "opts.rs", .name = "require_equals_pass", .status = .ported },
    .{ .file = "opts.rs", .name = "require_equals_empty_vals_pass", .status = .ported },
    .{ .file = "opts.rs", .name = "opts_using_short", .status = .ported },
    .{ .file = "opts.rs", .name = "opts_using_long_space", .status = .ported },
    .{ .file = "opts.rs", .name = "opts_using_long_equals", .status = .ported },
    .{ .file = "opts.rs", .name = "opts_using_mixed", .status = .ported },
    .{ .file = "opts.rs", .name = "opts_using_mixed2", .status = .ported },
    .{ .file = "opts.rs", .name = "default_values_user_value", .status = .ported },
    .{ .file = "opts.rs", .name = "stdin_char", .status = .ported },
    .{ .file = "opts.rs", .name = "multiple_vals_pos_arg_equals", .status = .ported },
    .{ .file = "opts.rs", .name = "double_hyphen_as_value", .status = .deferred, .note = "allow_hyphen_values" },
    .{ .file = "opts.rs", .name = "require_equals_no_empty_values_fail", .status = .deferred, .note = "NonEmptyStringValueParser" },
    .{ .file = "opts.rs", .name = "lots_o_vals", .status = .deferred, .note = "multi-value options (num_args>1)" },
    .{ .file = "opts.rs", .name = "require_delims_no_delim", .status = .deferred, .note = "value_delimiter num_args greediness" },
    .{ .file = "opts.rs", .name = "require_delims", .status = .deferred, .note = "value_delimiter num_args greediness" },

    // ----- flags.rs -----
    .{ .file = "flags.rs", .name = "flag_using_short", .status = .ported },
    .{ .file = "flags.rs", .name = "flag_using_long", .status = .ported },
    .{ .file = "flags.rs", .name = "flag_using_long_with_literals", .status = .ported },
    .{ .file = "flags.rs", .name = "flag_using_mixed", .status = .ported },
    .{ .file = "flags.rs", .name = "multiple_flags_in_single", .status = .ported },
    .{ .file = "flags.rs", .name = "unexpected_value_error", .status = .ported },
    .{ .file = "flags.rs", .name = "lots_o_flags_sep", .status = .deferred, .note = "args_override_self" },
    .{ .file = "flags.rs", .name = "lots_o_flags_combined", .status = .deferred, .note = "args_override_self" },
    .{ .file = "flags.rs", .name = "issue_1284_argument_in_flag_style", .status = .deferred, .note = "error trailing-arg tip" },
    .{ .file = "flags.rs", .name = "issue_2308_multiple_dashes", .status = .deferred, .note = "error trailing-arg tip" },
    .{ .file = "flags.rs", .name = "leading_dash_stripped", .status = .deferred, .note = "debug_assert" },
    .{ .file = "flags.rs", .name = "optional_value", .status = .deferred, .note = "optional-value SetTrue (num_args 0..=1)" },

    // ----- positionals.rs -----
    .{ .file = "positionals.rs", .name = "only_pos_follow", .status = .ported },
    .{ .file = "positionals.rs", .name = "positional", .status = .ported },
    .{ .file = "positionals.rs", .name = "lots_o_vals", .status = .ported },
    .{ .file = "positionals.rs", .name = "positional_multiple", .status = .ported },
    .{ .file = "positionals.rs", .name = "positional_multiple_3", .status = .ported },
    .{ .file = "positionals.rs", .name = "positional_multiple_2", .status = .ported },
    .{ .file = "positionals.rs", .name = "positional_possible_values", .status = .ported },
    .{ .file = "positionals.rs", .name = "create_positional", .status = .ported },
    .{ .file = "positionals.rs", .name = "positional_hyphen_does_not_panic", .status = .ported },
    .{ .file = "positionals.rs", .name = "single_positional_usage_string", .status = .ported },
    .{ .file = "positionals.rs", .name = "single_positional_multiple_usage_string", .status = .ported },
    .{ .file = "positionals.rs", .name = "multiple_positional_usage_string", .status = .ported },
    .{ .file = "positionals.rs", .name = "multiple_positional_one_required_usage_string", .status = .ported },
    .{ .file = "positionals.rs", .name = "single_positional_required_usage_string", .status = .ported },
    .{ .file = "positionals.rs", .name = "missing_required_2", .status = .ported },
    .{ .file = "positionals.rs", .name = "last_positional", .status = .ported },
    .{ .file = "positionals.rs", .name = "last_positional_no_double_dash", .status = .ported },
    .{ .file = "positionals.rs", .name = "last_positional_second_to_last_mult", .status = .ported },
    .{ .file = "positionals.rs", .name = "missing_required", .status = .deferred, .note = "debug_assert" },
    .{ .file = "positionals.rs", .name = "positional_arg_with_long", .status = .deferred, .note = "debug_assert" },
    .{ .file = "positionals.rs", .name = "positional_arg_with_short", .status = .deferred, .note = "debug_assert" },
    .{ .file = "positionals.rs", .name = "ignore_hyphen_values_on_last", .status = .deferred, .note = "allow_hyphen_values" },

    // ----- possible_values.rs -----
    .{ .file = "possible_values.rs", .name = "possible_values_of_positional", .status = .ported },
    .{ .file = "possible_values.rs", .name = "possible_value_arg_value", .status = .ported },
    .{ .file = "possible_values.rs", .name = "possible_values_of_positional_fail", .status = .ported },
    .{ .file = "possible_values.rs", .name = "possible_values_of_positional_multiple", .status = .ported },
    .{ .file = "possible_values.rs", .name = "possible_values_of_positional_multiple_fail", .status = .ported },
    .{ .file = "possible_values.rs", .name = "possible_values_of_option", .status = .ported },
    .{ .file = "possible_values.rs", .name = "possible_values_of_option_fail", .status = .ported },
    .{ .file = "possible_values.rs", .name = "possible_values_of_option_multiple", .status = .ported },
    .{ .file = "possible_values.rs", .name = "possible_values_of_option_multiple_fail", .status = .ported },
    .{ .file = "possible_values.rs", .name = "ignore_case_fail", .status = .ported },
    .{ .file = "possible_values.rs", .name = "possible_values_output", .status = .ported },
    .{ .file = "possible_values.rs", .name = "possible_values_alias_output", .status = .deferred, .note = "PossibleValue aliases" },
    .{ .file = "possible_values.rs", .name = "possible_values_hidden_output", .status = .deferred, .note = "PossibleValue.hide" },
    .{ .file = "possible_values.rs", .name = "escaped_possible_values_output", .status = .ported },
    .{ .file = "possible_values.rs", .name = "missing_possible_value_error", .status = .deferred, .note = "value-required error" },
    .{ .file = "possible_values.rs", .name = "alias", .status = .deferred, .note = "value aliases" },
    .{ .file = "possible_values.rs", .name = "aliases", .status = .deferred, .note = "value aliases" },
    .{ .file = "possible_values.rs", .name = "ignore_case", .status = .deferred, .note = "ignore_case" },
    .{ .file = "possible_values.rs", .name = "ignore_case_multiple", .status = .deferred, .note = "ignore_case" },
    .{ .file = "possible_values.rs", .name = "ignore_case_multiple_fail", .status = .ported },

    // ----- indices.rs -----
    .{ .file = "indices.rs", .name = "index_flag", .status = .ported },
    .{ .file = "indices.rs", .name = "index_flags", .status = .ported },
    .{ .file = "indices.rs", .name = "indices_mult_flags", .status = .ported },
    .{ .file = "indices.rs", .name = "indices_mult_flags_combined", .status = .ported },
    .{ .file = "indices.rs", .name = "indices_mult_flags_opt_combined", .status = .ported },
    .{ .file = "indices.rs", .name = "indices_mult_flags_opt_combined_eq", .status = .ported },
    .{ .file = "indices.rs", .name = "indices_mult_opt_mult_flag", .status = .ported },
    .{ .file = "indices.rs", .name = "indices_mult_opts", .status = .ported },
    .{ .file = "indices.rs", .name = "index_mult_opts", .status = .ported },
    .{ .file = "indices.rs", .name = "indices_mult_opt_value_delim_eq", .status = .deferred, .note = "value_delimiter" },
    .{ .file = "indices.rs", .name = "indices_mult_opt_value_no_delim_eq", .status = .ported },

    // ----- action.rs -----
    .{ .file = "action.rs", .name = "set", .status = .ported },
    .{ .file = "action.rs", .name = "append", .status = .ported },
    .{ .file = "action.rs", .name = "set_true", .status = .ported },
    .{ .file = "action.rs", .name = "set_true_with_explicit_default_value", .status = .ported },
    .{ .file = "action.rs", .name = "set_true_with_default_value_if_present", .status = .deferred, .note = "default_value_if" },
    .{ .file = "action.rs", .name = "set_true_with_default_value_if_value", .status = .deferred, .note = "default_value_if" },
    .{ .file = "action.rs", .name = "set_true_with_required_if_eq", .status = .deferred, .note = "required_if_eq" },
    .{ .file = "action.rs", .name = "set_true_with_incompatible_num_args", .status = .deferred, .note = "debug_assert" },
    .{ .file = "action.rs", .name = "set_false", .status = .ported },
    .{ .file = "action.rs", .name = "set_false_with_explicit_default_value", .status = .ported },
    .{ .file = "action.rs", .name = "set_false_with_default_value_if_present", .status = .deferred, .note = "default_value_if" },
    .{ .file = "action.rs", .name = "set_false_with_default_value_if_value", .status = .deferred, .note = "default_value_if" },
    .{ .file = "action.rs", .name = "set_false_with_incompatible_num_args", .status = .deferred, .note = "debug_assert" },
    .{ .file = "action.rs", .name = "count", .status = .ported },
    .{ .file = "action.rs", .name = "count_with_explicit_default_value", .status = .ported },
    .{ .file = "action.rs", .name = "count_with_default_value_if_present", .status = .ported },
    .{ .file = "action.rs", .name = "count_with_default_value_if_value", .status = .ported },
    .{ .file = "action.rs", .name = "count_with_incompatible_num_args", .status = .deferred, .note = "debug_assert" },
    .{ .file = "action.rs", .name = "help_with_incompatible_num_args", .status = .deferred, .note = "debug_assert" },
    .{ .file = "action.rs", .name = "help_short_with_incompatible_num_args", .status = .deferred, .note = "debug_assert" },
    .{ .file = "action.rs", .name = "help_long_with_incompatible_num_args", .status = .deferred, .note = "debug_assert" },
    .{ .file = "action.rs", .name = "version_with_incompatible_num_args", .status = .deferred, .note = "debug_assert" },

    // ----- multiple_values.rs (option & positional multi-value; rest pending) -----
    .{ .file = "multiple_values.rs", .name = "option_long", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "option_short", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "option_mixed", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "option_exact_exact", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "option_exact_exact_not_mult", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "option_exact_exact_mult", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "option_exact_less", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "option_exact_more", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "option_min_exact", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "option_min_less", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "option_short_min_more_mult_occurs", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "option_short_min_more_single_occur", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "option_max_exact", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "option_max_less", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "option_max_zero", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "option_max_zero_eq", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "option_max_more", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "optional_value", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "positional", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "positional_exact_exact", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "positional_min_exact", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "positional_min_more", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "positional_max_exact", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "positional_max_less", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "positional_exact_less", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "positional_exact_more", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "positional_min_less", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "positional_max_more", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "multiple_value_terminator_option", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "multiple_value_terminator_positional", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "value_terminator_has_higher_precedence_than_allow_hyphen_values", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "escape_like_value_terminator", .status = .deferred, .note = "value_terminator '--' escape-like edge cases" },
    .{ .file = "multiple_values.rs", .name = "escape_like_value_terminator_and_allow_hyphen_values", .status = .deferred, .note = "value_terminator '--' escape-like edge cases" },
    .{ .file = "multiple_values.rs", .name = "escape_like_value_terminator_and_last", .status = .deferred, .note = "value_terminator '--' + last" },

    // ----- help.rs (self-contained cases; complex_app/template/wrap/global ones pending) -----
    .{ .file = "help.rs", .name = "help_short", .status = .ported },
    .{ .file = "help.rs", .name = "help_long", .status = .ported },
    .{ .file = "help.rs", .name = "help_no_subcommand", .status = .ported },
    .{ .file = "help.rs", .name = "help_subcommand", .status = .ported },
    .{ .file = "help.rs", .name = "req_last_arg_usage", .status = .ported },
    .{ .file = "help.rs", .name = "last_arg_mult_usage", .status = .ported },
    .{ .file = "help.rs", .name = "last_arg_mult_usage_req", .status = .ported },
    .{ .file = "help.rs", .name = "issue_1487", .status = .ported },
    .{ .file = "help.rs", .name = "option_usage_order", .status = .ported },
    .{ .file = "help.rs", .name = "args_negate_sc", .status = .deferred, .note = "args_conflicts two-line usage" },

    // ----- tests.rs (complex_app parse matrix; global flag now supported) -----
    .{ .file = "tests.rs", .name = "create_app", .status = .ported },
    .{ .file = "tests.rs", .name = "add_multiple_arg", .status = .ported },
    .{ .file = "tests.rs", .name = "flag_x2_opt", .status = .ported },
    .{ .file = "tests.rs", .name = "long_opt_x2_pos", .status = .ported },
    .{ .file = "tests.rs", .name = "long_opt_eq_x2_pos", .status = .ported },
    .{ .file = "tests.rs", .name = "short_opt_x2_pos", .status = .ported },
    .{ .file = "tests.rs", .name = "short_opt_eq_x2_pos", .status = .ported },
    .{ .file = "tests.rs", .name = "short_flag_x2_comb_short_opt_pos", .status = .ported },
    .{ .file = "tests.rs", .name = "short_flag_short_opt_pos", .status = .ported },
    .{ .file = "tests.rs", .name = "long_flag_long_opt_pos", .status = .ported },
    .{ .file = "tests.rs", .name = "long_flag_long_opt_eq_pos", .status = .ported },
    .{ .file = "tests.rs", .name = "sc_long_flag_long_opt", .status = .ported },
    .{ .file = "tests.rs", .name = "sc_long_flag_short_opt_pos", .status = .ported },
    .{ .file = "tests.rs", .name = "sc_long_flag_long_opt_eq_pos", .status = .ported },
    .{ .file = "tests.rs", .name = "sc_short_flag_long_opt_pos", .status = .ported },
    .{ .file = "tests.rs", .name = "sc_short_flag_short_opt_pos", .status = .ported },
    .{ .file = "tests.rs", .name = "sc_short_flag_short_opt_eq_pos", .status = .ported },
    .{ .file = "tests.rs", .name = "sc_short_flag_long_opt_eq_pos", .status = .ported },
    .{ .file = "tests.rs", .name = "sc_short_flag_x2_comb_long_opt_pos", .status = .ported },
    .{ .file = "tests.rs", .name = "sc_short_flag_x2_comb_short_opt_pos", .status = .ported },
    .{ .file = "tests.rs", .name = "sc_short_flag_x2_comb_long_opt_eq_pos", .status = .ported },
    .{ .file = "tests.rs", .name = "sc_short_flag_x2_comb_short_opt_eq_pos", .status = .ported },
    .{ .file = "tests.rs", .name = "sc_long_flag_x2_long_opt_pos", .status = .ported },
    .{ .file = "tests.rs", .name = "sc_long_flag_x2_short_opt_pos", .status = .ported },
    .{ .file = "tests.rs", .name = "sc_long_flag_x2_short_opt_eq_pos", .status = .ported },
    .{ .file = "tests.rs", .name = "sc_long_flag_x2_long_opt_eq_pos", .status = .ported },
    .{ .file = "tests.rs", .name = "sc_short_flag_x2_long_opt_pos", .status = .ported },
    .{ .file = "tests.rs", .name = "sc_short_flag_x2_short_opt_pos", .status = .ported },
    .{ .file = "tests.rs", .name = "sc_short_flag_x2_short_opt_eq_pos", .status = .ported },
    .{ .file = "tests.rs", .name = "sc_short_flag_x2_long_opt_eq_pos", .status = .ported },
    .{ .file = "tests.rs", .name = "mut_arg_all", .status = .deferred, .note = "mut_arg" },
    .{ .file = "tests.rs", .name = "mut_subcommand_all", .status = .deferred, .note = "mut_subcommand" },
    .{ .file = "tests.rs", .name = "mut_subcommand_with_alias_resolve", .status = .deferred, .note = "aliases" },
    .{ .file = "tests.rs", .name = "issue_3669_command_build_recurses", .status = .deferred, .note = "build recursion API" },

    // ----- conflicts.rs -----
    .{ .file = "conflicts.rs", .name = "flag_conflict", .status = .ported },
    .{ .file = "conflicts.rs", .name = "flag_conflict_2", .status = .ported },
    .{ .file = "conflicts.rs", .name = "flag_conflict_with_all", .status = .ported },
    .{ .file = "conflicts.rs", .name = "exclusive_flag", .status = .ported },
    .{ .file = "conflicts.rs", .name = "exclusive_option", .status = .ported },
    .{ .file = "conflicts.rs", .name = "not_exclusive_with_defaults", .status = .ported },
    .{ .file = "conflicts.rs", .name = "default_doesnt_activate_exclusive", .status = .ported },
    .{ .file = "conflicts.rs", .name = "conflict_output", .status = .ported },
    .{ .file = "conflicts.rs", .name = "conflict_output_rev", .status = .ported },
    .{ .file = "conflicts.rs", .name = "conflict_output_repeat", .status = .ported },
    .{ .file = "conflicts.rs", .name = "conflict_output_with_required", .status = .ported },
    .{ .file = "conflicts.rs", .name = "conflict_output_rev_with_required", .status = .ported },
    .{ .file = "conflicts.rs", .name = "conflict_output_three_conflicting", .status = .ported },
    .{ .file = "conflicts.rs", .name = "two_conflicting_arguments", .status = .ported },
    .{ .file = "conflicts.rs", .name = "three_conflicting_arguments", .status = .ported },
    .{ .file = "conflicts.rs", .name = "conflict_with_unused_default", .status = .ported },
    .{ .file = "conflicts.rs", .name = "conflicts_with_alongside_default", .status = .ported },
    // deferred: arg<->group cross-conflicts (conflicts_with naming a group / group.conflicts_with)
    .{ .file = "conflicts.rs", .name = "not_exclusive_with_group", .status = .deferred, .note = "arg-group conflicts" },
    .{ .file = "conflicts.rs", .name = "arg_conflicts_with_group", .status = .deferred, .note = "arg-group conflicts" },
    .{ .file = "conflicts.rs", .name = "arg_conflicts_with_group_with_multiple_sources", .status = .deferred, .note = "arg-group conflicts" },
    .{ .file = "conflicts.rs", .name = "group_conflicts_with_arg", .status = .deferred, .note = "arg-group conflicts" },
    .{ .file = "conflicts.rs", .name = "arg_conflicts_with_required_group", .status = .deferred, .note = "arg-group conflicts" },
    .{ .file = "conflicts.rs", .name = "arg_conflicts_with_group_with_required_memeber", .status = .deferred, .note = "arg-group conflicts" },
    .{ .file = "conflicts.rs", .name = "required_group_conflicts_with_arg", .status = .deferred, .note = "arg-group conflicts" },
    .{ .file = "conflicts.rs", .name = "get_arg_conflicts_with_group", .status = .deferred, .note = "get_arg_conflicts_with API" },
    .{ .file = "conflicts.rs", .name = "group_in_conflicts_with", .status = .deferred, .note = "arg-group conflicts" },
    .{ .file = "conflicts.rs", .name = "group_conflicts_with_default_value", .status = .deferred, .note = "arg-group conflicts" },
    .{ .file = "conflicts.rs", .name = "group_conflicts_with_default_arg", .status = .deferred, .note = "arg-group conflicts" },
    // deferred: debug_assert build-time panics
    .{ .file = "conflicts.rs", .name = "self_conflicting_arg", .status = .deferred, .note = "debug_assert" },
    .{ .file = "conflicts.rs", .name = "conflicts_with_invalid_arg", .status = .deferred, .note = "debug_assert" },
    // deferred: exclusive interacting with required_unless_present (task #11)
    .{ .file = "conflicts.rs", .name = "exclusive_with_required", .status = .deferred, .note = "required_unless_present" },
    .{ .file = "conflicts.rs", .name = "exclusive_with_required_unless_present", .status = .deferred, .note = "required_unless_present" },
    .{ .file = "conflicts.rs", .name = "exclusive_with_required_unless_present_any", .status = .deferred, .note = "required_unless_present" },
    .{ .file = "conflicts.rs", .name = "exclusive_with_required_unless_present_all", .status = .deferred, .note = "required_unless_present" },
    // deferred: conflicts between args and subcommands / flag-subcommands
    .{ .file = "conflicts.rs", .name = "option_conflicts_with_subcommand", .status = .deferred, .note = "arg-subcommand conflicts" },
    .{ .file = "conflicts.rs", .name = "positional_conflicts_with_subcommand", .status = .deferred, .note = "arg-subcommand conflicts" },
    .{ .file = "conflicts.rs", .name = "flag_conflicts_with_subcommand_long_flag", .status = .deferred, .note = "flag_subcommand" },
    .{ .file = "conflicts.rs", .name = "flag_conflicts_with_subcommand_short_flag", .status = .deferred, .note = "flag_subcommand" },
    .{ .file = "conflicts.rs", .name = "positional_conflicts_with_subcommand_precedent", .status = .deferred, .note = "arg-subcommand conflicts" },
    .{ .file = "conflicts.rs", .name = "flag_conflicts_with_subcommand_precedent", .status = .deferred, .note = "flag_subcommand" },
    .{ .file = "conflicts.rs", .name = "subcommand_conflict_negates_required", .status = .deferred, .note = "subcommand_negates_reqs" },
    .{ .file = "conflicts.rs", .name = "args_negate_subcommands_one_level", .status = .deferred, .note = "subcommand_negates_reqs" },
    .{ .file = "conflicts.rs", .name = "args_negate_subcommands_two_levels", .status = .deferred, .note = "subcommand_negates_reqs" },
    .{ .file = "conflicts.rs", .name = "group_conrflicts_with_subcommands", .status = .deferred, .note = "arg-group conflicts" },

    // ----- posix_compatible.rs (overrides_with) -----
    .{ .file = "posix_compatible.rs", .name = "flag_overrides_itself", .status = .ported },
    .{ .file = "posix_compatible.rs", .name = "option_overrides_itself", .status = .ported },
    .{ .file = "posix_compatible.rs", .name = "posix_compatible_flags_long", .status = .ported },
    .{ .file = "posix_compatible.rs", .name = "posix_compatible_flags_long_rev", .status = .ported },
    .{ .file = "posix_compatible.rs", .name = "posix_compatible_flags_short", .status = .ported },
    .{ .file = "posix_compatible.rs", .name = "posix_compatible_flags_short_rev", .status = .ported },
    .{ .file = "posix_compatible.rs", .name = "posix_compatible_opts_long", .status = .ported },
    .{ .file = "posix_compatible.rs", .name = "posix_compatible_opts_long_rev", .status = .ported },
    .{ .file = "posix_compatible.rs", .name = "posix_compatible_opts_long_equals", .status = .ported },
    .{ .file = "posix_compatible.rs", .name = "posix_compatible_opts_long_equals_rev", .status = .ported },
    .{ .file = "posix_compatible.rs", .name = "posix_compatible_opts_short", .status = .ported },
    .{ .file = "posix_compatible.rs", .name = "posix_compatible_opts_short_rev", .status = .ported },
    .{ .file = "posix_compatible.rs", .name = "conflict_overridden", .status = .ported },
    .{ .file = "posix_compatible.rs", .name = "conflict_overridden_2", .status = .ported },
    .{ .file = "posix_compatible.rs", .name = "conflict_overridden_3", .status = .ported },
    .{ .file = "posix_compatible.rs", .name = "conflict_overridden_4", .status = .ported },
    .{ .file = "posix_compatible.rs", .name = "pos_required_overridden_by_flag", .status = .ported },
    .{ .file = "posix_compatible.rs", .name = "require_overridden_2", .status = .ported },
    .{ .file = "posix_compatible.rs", .name = "require_overridden_3", .status = .ported },
    .{ .file = "posix_compatible.rs", .name = "require_overridden_4", .status = .ported },
    .{ .file = "posix_compatible.rs", .name = "incremental_override", .status = .ported },
    .{ .file = "posix_compatible.rs", .name = "overrides_with_invalid_arg", .status = .deferred, .note = "debug_assert" },

    // ----- require.rs (requires / requires_if / requires_ifs) -----
    .{ .file = "require.rs", .name = "flag_required", .status = .ported },
    .{ .file = "require.rs", .name = "flag_required_2", .status = .ported },
    .{ .file = "require.rs", .name = "option_required", .status = .ported },
    .{ .file = "require.rs", .name = "option_required_2", .status = .ported },
    .{ .file = "require.rs", .name = "positional_required", .status = .ported },
    .{ .file = "require.rs", .name = "positional_required_2", .status = .ported },
    .{ .file = "require.rs", .name = "positional_required_with_requires", .status = .ported },
    .{ .file = "require.rs", .name = "positional_required_with_requires_if_no_value", .status = .ported },
    .{ .file = "require.rs", .name = "positional_required_with_requires_if_value", .status = .ported },
    .{ .file = "require.rs", .name = "group_required", .status = .ported },
    .{ .file = "require.rs", .name = "group_required_2", .status = .ported },
    .{ .file = "require.rs", .name = "group_required_3", .status = .ported },
    .{ .file = "require.rs", .name = "arg_require_group", .status = .ported },
    .{ .file = "require.rs", .name = "arg_require_group_2", .status = .ported },
    .{ .file = "require.rs", .name = "arg_require_group_3", .status = .ported },
    .{ .file = "require.rs", .name = "missing_required_output", .status = .ported },
    .{ .file = "require.rs", .name = "requires_if_present_val", .status = .ported },
    .{ .file = "require.rs", .name = "requires_if_present_mult", .status = .ported },
    .{ .file = "require.rs", .name = "requires_if_present_mult_pass", .status = .ported },
    .{ .file = "require.rs", .name = "requires_if_present_val_no_present_pass", .status = .ported },
    .{ .file = "require.rs", .name = "list_correct_required_args", .status = .ported },
    // deferred: required_unless_present(_any/_all) — task #11
    .{ .file = "require.rs", .name = "required_unless_present", .status = .ported },
    .{ .file = "require.rs", .name = "required_unless_present_err", .status = .ported },
    .{ .file = "require.rs", .name = "required_unless_present_with_optional_value", .status = .ported },
    .{ .file = "require.rs", .name = "required_unless_present_all", .status = .ported },
    .{ .file = "require.rs", .name = "required_unless_all_err", .status = .ported },
    .{ .file = "require.rs", .name = "required_unless_present_any", .status = .ported },
    .{ .file = "require.rs", .name = "required_unless_any_2", .status = .ported },
    .{ .file = "require.rs", .name = "required_unless_any_works_with_short", .status = .ported },
    .{ .file = "require.rs", .name = "required_unless_any_works_with_short_err", .status = .ported },
    .{ .file = "require.rs", .name = "required_unless_any_works_without", .status = .ported },
    .{ .file = "require.rs", .name = "required_unless_any_works_with_long", .status = .ported },
    .{ .file = "require.rs", .name = "required_unless_any_1", .status = .ported },
    .{ .file = "require.rs", .name = "required_unless_any_err", .status = .ported },
    .{ .file = "require.rs", .name = "multiple_required_unless_usage_printing", .status = .ported },
    .{ .file = "require.rs", .name = "required_unless_all_with_any", .status = .ported },
    .{ .file = "require.rs", .name = "required_unless_invalid_arg", .status = .deferred, .note = "debug_assert" },
    .{ .file = "require.rs", .name = "required_unless_on_default_value", .status = .deferred, .note = "required_unless_present" },
    .{ .file = "require.rs", .name = "required_unless_all_on_default_value", .status = .deferred, .note = "required_unless_present" },
    // deferred: required_if_eq(_any/_all) — task #12
    .{ .file = "require.rs", .name = "required_if_val_present_pass", .status = .ported },
    .{ .file = "require.rs", .name = "required_if_val_present_fail", .status = .ported },
    .{ .file = "require.rs", .name = "required_if_val_present_ignore_case_pass", .status = .deferred, .note = "ignore_case" },
    .{ .file = "require.rs", .name = "required_if_val_present_ignore_case_fail", .status = .deferred, .note = "ignore_case" },
    .{ .file = "require.rs", .name = "required_if_all_values_present_pass", .status = .ported },
    .{ .file = "require.rs", .name = "required_if_some_values_present_pass", .status = .ported },
    .{ .file = "require.rs", .name = "required_if_all_values_present_fail", .status = .ported },
    .{ .file = "require.rs", .name = "required_if_any_all_values_present_pass", .status = .ported },
    .{ .file = "require.rs", .name = "required_if_any_all_values_present_fail", .status = .ported },
    .{ .file = "require.rs", .name = "required_if_val_present_fail_error_output", .status = .ported },
    .{ .file = "require.rs", .name = "required_if_wrong_val", .status = .ported },
    .{ .file = "require.rs", .name = "required_ifs_val_present_pass", .status = .ported },
    .{ .file = "require.rs", .name = "required_ifs_val_present_fail", .status = .ported },
    .{ .file = "require.rs", .name = "required_ifs_wrong_val", .status = .ported },
    .{ .file = "require.rs", .name = "required_ifs_wrong_val_mult_fail", .status = .ported },
    .{ .file = "require.rs", .name = "require_eq", .status = .deferred, .note = "required_if_eq" },
    .{ .file = "require.rs", .name = "require_eq_filtered", .status = .deferred, .note = "required_if_eq" },
    .{ .file = "require.rs", .name = "require_eq_filtered_group", .status = .deferred, .note = "required_if_eq" },
    .{ .file = "require.rs", .name = "required_if_invalid_arg", .status = .deferred, .note = "debug_assert" },
    .{ .file = "require.rs", .name = "required_if_eq_on_default_value", .status = .deferred, .note = "required_if_eq" },
    .{ .file = "require.rs", .name = "required_if_eq_all_on_default_value", .status = .deferred, .note = "required_if_eq" },
    // deferred: misc require edge cases
    .{ .file = "require.rs", .name = "issue_753", .status = .deferred, .note = "arg-group conflicts" },
    .{ .file = "require.rs", .name = "issue_1158_conflicting_requirements", .status = .deferred, .note = "required_unless_present" },
    .{ .file = "require.rs", .name = "issue_1158_conflicting_requirements_rev", .status = .deferred, .note = "required_unless_present" },
    .{ .file = "require.rs", .name = "issue_1643_args_mutually_require_each_other", .status = .deferred, .note = "mutual requires" },
    .{ .file = "require.rs", .name = "short_flag_require_equals_with_minvals_zero", .status = .deferred, .note = "min_values 0 require_equals" },
    .{ .file = "require.rs", .name = "issue_2624", .status = .deferred, .note = "required_if_eq" },
    .{ .file = "require.rs", .name = "requires_invalid_arg", .status = .deferred, .note = "debug_assert" },
    .{ .file = "require.rs", .name = "requires_if_invalid_arg", .status = .deferred, .note = "debug_assert" },
    .{ .file = "require.rs", .name = "requires_with_default_value", .status = .deferred, .note = "requires vs default_value" },
    .{ .file = "require.rs", .name = "requires_if_with_default_value", .status = .deferred, .note = "requires vs default_value" },
    .{ .file = "require.rs", .name = "group_requires_with_default_value", .status = .deferred, .note = "group requires" },
    .{ .file = "require.rs", .name = "required_error_doesnt_duplicate", .status = .deferred, .note = "required_unless_present" },
    .{ .file = "require.rs", .name = "required_require_with_group_shows_flag", .status = .deferred, .note = "group requires" },
    .{ .file = "require.rs", .name = "requires_self", .status = .deferred, .note = "debug_assert" },
};
