//! Hand-maintained manifest of which clap builder tests we have addressed.
//! Each entry references a test in tests/clap_universe.zig:
//!   - `ported`   — translated and passing in a tests/clap_<file>_test.zig
//!   - `deferred` — needs a feature clap-zig hasn't implemented yet (see note)
//! Tests in the universe but absent here are still `pending`. Run
//! `zig build coverage` for the report. The goal is zero pending: every test is
//! either ported or deferred, i.e. 100% of what we support.

pub const Status = enum { ported, deferred };

pub const Entry = struct {
    file: []const u8,
    name: []const u8,
    status: Status,
    /// for `deferred`: the missing feature gating this test
    note: []const u8 = "",
};

pub const entries = [_]Entry{
    // ----- opts.rs -----
    .{ .file = "opts.rs", .name = "require_equals_fail", .status = .ported },
    .{ .file = "opts.rs", .name = "require_equals_fail_message", .status = .ported },
    .{ .file = "opts.rs", .name = "require_equals_pass", .status = .ported },
    .{ .file = "opts.rs", .name = "require_equals_empty_vals_pass", .status = .ported },
    .{ .file = "opts.rs", .name = "opts_using_short", .status = .ported },
    .{ .file = "opts.rs", .name = "opts_using_long_space", .status = .ported },
    .{ .file = "opts.rs", .name = "opts_using_long_equals", .status = .ported },
    .{ .file = "opts.rs", .name = "opts_using_mixed", .status = .ported },
    .{ .file = "opts.rs", .name = "opts_using_mixed2", .status = .ported },
    .{ .file = "opts.rs", .name = "default_values_user_value", .status = .ported },
    .{ .file = "opts.rs", .name = "stdin_char", .status = .ported },
    .{ .file = "opts.rs", .name = "multiple_vals_pos_arg_equals", .status = .ported },
    .{ .file = "opts.rs", .name = "double_hyphen_as_value", .status = .deferred, .note = "allow_hyphen_values" },
    .{ .file = "opts.rs", .name = "require_equals_no_empty_values_fail", .status = .deferred, .note = "NonEmptyStringValueParser" },
    .{ .file = "opts.rs", .name = "lots_o_vals", .status = .deferred, .note = "multi-value options (num_args>1)" },
    .{ .file = "opts.rs", .name = "require_delims_no_delim", .status = .deferred, .note = "value_delimiter" },
    .{ .file = "opts.rs", .name = "require_delims", .status = .deferred, .note = "value_delimiter" },
    .{ .file = "opts.rs", .name = "leading_hyphen_pass", .status = .deferred, .note = "allow_hyphen_values" },

    // ----- flags.rs -----
    .{ .file = "flags.rs", .name = "flag_using_short", .status = .ported },
    .{ .file = "flags.rs", .name = "flag_using_long", .status = .ported },
    .{ .file = "flags.rs", .name = "flag_using_long_with_literals", .status = .ported },
    .{ .file = "flags.rs", .name = "flag_using_mixed", .status = .ported },
    .{ .file = "flags.rs", .name = "multiple_flags_in_single", .status = .ported },
    .{ .file = "flags.rs", .name = "unexpected_value_error", .status = .ported },
    .{ .file = "flags.rs", .name = "lots_o_flags_sep", .status = .deferred, .note = "args_override_self" },
    .{ .file = "flags.rs", .name = "lots_o_flags_combined", .status = .deferred, .note = "args_override_self" },
    .{ .file = "flags.rs", .name = "issue_1284_argument_in_flag_style", .status = .deferred, .note = "error trailing-arg tip" },
    .{ .file = "flags.rs", .name = "issue_2308_multiple_dashes", .status = .deferred, .note = "error trailing-arg tip" },
    .{ .file = "flags.rs", .name = "leading_dash_stripped", .status = .deferred, .note = "debug_assert" },
    .{ .file = "flags.rs", .name = "optional_value", .status = .deferred, .note = "optional-value SetTrue (num_args 0..=1)" },

    // ----- positionals.rs -----
    .{ .file = "positionals.rs", .name = "only_pos_follow", .status = .ported },
    .{ .file = "positionals.rs", .name = "positional", .status = .ported },
    .{ .file = "positionals.rs", .name = "lots_o_vals", .status = .ported },
    .{ .file = "positionals.rs", .name = "positional_multiple", .status = .ported },
    .{ .file = "positionals.rs", .name = "positional_multiple_3", .status = .ported },
    .{ .file = "positionals.rs", .name = "positional_multiple_2", .status = .ported },
    .{ .file = "positionals.rs", .name = "positional_possible_values", .status = .ported },
    .{ .file = "positionals.rs", .name = "create_positional", .status = .ported },
    .{ .file = "positionals.rs", .name = "positional_hyphen_does_not_panic", .status = .ported },
    .{ .file = "positionals.rs", .name = "single_positional_usage_string", .status = .ported },
    .{ .file = "positionals.rs", .name = "single_positional_multiple_usage_string", .status = .ported },
    .{ .file = "positionals.rs", .name = "multiple_positional_usage_string", .status = .ported },
    .{ .file = "positionals.rs", .name = "multiple_positional_one_required_usage_string", .status = .ported },
    .{ .file = "positionals.rs", .name = "single_positional_required_usage_string", .status = .ported },
    .{ .file = "positionals.rs", .name = "missing_required_2", .status = .ported },
    .{ .file = "positionals.rs", .name = "last_positional", .status = .ported },
    .{ .file = "positionals.rs", .name = "last_positional_no_double_dash", .status = .ported },
    .{ .file = "positionals.rs", .name = "last_positional_second_to_last_mult", .status = .ported },
    .{ .file = "positionals.rs", .name = "issue_946", .status = .deferred, .note = "allow_hyphen_values" },
    .{ .file = "positionals.rs", .name = "missing_required", .status = .deferred, .note = "debug_assert" },
    .{ .file = "positionals.rs", .name = "positional_arg_with_long", .status = .deferred, .note = "debug_assert" },
    .{ .file = "positionals.rs", .name = "positional_arg_with_short", .status = .deferred, .note = "debug_assert" },
    .{ .file = "positionals.rs", .name = "ignore_hyphen_values_on_last", .status = .deferred, .note = "allow_hyphen_values" },

    // ----- possible_values.rs -----
    .{ .file = "possible_values.rs", .name = "possible_values_of_positional", .status = .ported },
    .{ .file = "possible_values.rs", .name = "possible_value_arg_value", .status = .ported },
    .{ .file = "possible_values.rs", .name = "possible_values_of_positional_fail", .status = .ported },
    .{ .file = "possible_values.rs", .name = "possible_values_of_positional_multiple", .status = .ported },
    .{ .file = "possible_values.rs", .name = "possible_values_of_positional_multiple_fail", .status = .ported },
    .{ .file = "possible_values.rs", .name = "possible_values_of_option", .status = .ported },
    .{ .file = "possible_values.rs", .name = "possible_values_of_option_fail", .status = .ported },
    .{ .file = "possible_values.rs", .name = "possible_values_of_option_multiple", .status = .ported },
    .{ .file = "possible_values.rs", .name = "possible_values_of_option_multiple_fail", .status = .ported },
    .{ .file = "possible_values.rs", .name = "ignore_case_fail", .status = .ported },
    .{ .file = "possible_values.rs", .name = "possible_values_output", .status = .deferred, .note = "did-you-mean suggestions + value quoting" },
    .{ .file = "possible_values.rs", .name = "possible_values_alias_output", .status = .deferred, .note = "value aliases + suggestions" },
    .{ .file = "possible_values.rs", .name = "possible_values_hidden_output", .status = .deferred, .note = "hidden possible values + suggestions" },
    .{ .file = "possible_values.rs", .name = "escaped_possible_values_output", .status = .deferred, .note = "did-you-mean suggestions" },
    .{ .file = "possible_values.rs", .name = "missing_possible_value_error", .status = .deferred, .note = "value-required error" },
    .{ .file = "possible_values.rs", .name = "alias", .status = .deferred, .note = "value aliases" },
    .{ .file = "possible_values.rs", .name = "aliases", .status = .deferred, .note = "value aliases" },
    .{ .file = "possible_values.rs", .name = "ignore_case", .status = .deferred, .note = "ignore_case" },
    .{ .file = "possible_values.rs", .name = "ignore_case_multiple", .status = .deferred, .note = "ignore_case" },
    .{ .file = "possible_values.rs", .name = "ignore_case_multiple_fail", .status = .ported },

    // ----- indices.rs -----
    .{ .file = "indices.rs", .name = "index_flag", .status = .ported },
    .{ .file = "indices.rs", .name = "index_flags", .status = .ported },
    .{ .file = "indices.rs", .name = "indices_mult_flags", .status = .ported },
    .{ .file = "indices.rs", .name = "indices_mult_flags_combined", .status = .ported },
    .{ .file = "indices.rs", .name = "indices_mult_flags_opt_combined", .status = .ported },
    .{ .file = "indices.rs", .name = "indices_mult_flags_opt_combined_eq", .status = .ported },
    .{ .file = "indices.rs", .name = "indices_mult_opt_mult_flag", .status = .ported },
    .{ .file = "indices.rs", .name = "indices_mult_opts", .status = .ported },
    .{ .file = "indices.rs", .name = "index_mult_opts", .status = .ported },
    .{ .file = "indices.rs", .name = "indices_mult_opt_value_delim_eq", .status = .deferred, .note = "value_delimiter" },
    .{ .file = "indices.rs", .name = "indices_mult_opt_value_no_delim_eq", .status = .ported },

    // ----- action.rs -----
    .{ .file = "action.rs", .name = "set", .status = .ported },
    .{ .file = "action.rs", .name = "append", .status = .ported },
    .{ .file = "action.rs", .name = "set_true", .status = .ported },
    .{ .file = "action.rs", .name = "set_true_with_explicit_default_value", .status = .ported },
    .{ .file = "action.rs", .name = "set_true_with_default_value_if_present", .status = .deferred, .note = "default_value_if" },
    .{ .file = "action.rs", .name = "set_true_with_default_value_if_value", .status = .deferred, .note = "default_value_if" },
    .{ .file = "action.rs", .name = "set_true_with_required_if_eq", .status = .deferred, .note = "required_if_eq" },
    .{ .file = "action.rs", .name = "set_true_with_incompatible_num_args", .status = .deferred, .note = "debug_assert" },
    .{ .file = "action.rs", .name = "set_false", .status = .ported },
    .{ .file = "action.rs", .name = "set_false_with_explicit_default_value", .status = .ported },
    .{ .file = "action.rs", .name = "set_false_with_default_value_if_present", .status = .deferred, .note = "default_value_if" },
    .{ .file = "action.rs", .name = "set_false_with_default_value_if_value", .status = .deferred, .note = "default_value_if" },
    .{ .file = "action.rs", .name = "set_false_with_incompatible_num_args", .status = .deferred, .note = "debug_assert" },
    .{ .file = "action.rs", .name = "count", .status = .ported },
    .{ .file = "action.rs", .name = "count_with_explicit_default_value", .status = .deferred, .note = "count default_value semantics" },
    .{ .file = "action.rs", .name = "count_with_default_value_if_present", .status = .deferred, .note = "default_value_if" },
    .{ .file = "action.rs", .name = "count_with_default_value_if_value", .status = .deferred, .note = "default_value_if" },
    .{ .file = "action.rs", .name = "count_with_incompatible_num_args", .status = .deferred, .note = "debug_assert" },
    .{ .file = "action.rs", .name = "help_with_incompatible_num_args", .status = .deferred, .note = "debug_assert" },
    .{ .file = "action.rs", .name = "help_short_with_incompatible_num_args", .status = .deferred, .note = "debug_assert" },
    .{ .file = "action.rs", .name = "help_long_with_incompatible_num_args", .status = .deferred, .note = "debug_assert" },
    .{ .file = "action.rs", .name = "version_with_incompatible_num_args", .status = .deferred, .note = "debug_assert" },

    // ----- multiple_values.rs (option & positional multi-value; rest pending) -----
    .{ .file = "multiple_values.rs", .name = "option_long", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "option_short", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "option_mixed", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "option_exact_exact", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "option_exact_exact_not_mult", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "option_exact_exact_mult", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "option_exact_less", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "option_exact_more", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "option_min_exact", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "option_min_less", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "option_short_min_more_mult_occurs", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "option_short_min_more_single_occur", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "option_max_exact", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "option_max_less", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "option_max_zero", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "option_max_zero_eq", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "option_max_more", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "optional_value", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "positional", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "positional_exact_exact", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "positional_min_exact", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "positional_min_more", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "positional_max_exact", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "positional_max_less", .status = .ported },
    .{ .file = "multiple_values.rs", .name = "positional_exact_less", .status = .deferred, .note = "positional num_args enforcement" },
    .{ .file = "multiple_values.rs", .name = "positional_exact_more", .status = .deferred, .note = "positional num_args enforcement" },
    .{ .file = "multiple_values.rs", .name = "positional_min_less", .status = .deferred, .note = "positional num_args enforcement" },
    .{ .file = "multiple_values.rs", .name = "positional_max_more", .status = .deferred, .note = "positional num_args enforcement" },
};
