#!/usr/bin/env bash
# Regenerate tests/clap_universe.zig — the full list of clap builder test
# functions, which is the denominator for our coverage tracking.
#
# Source: a local checkout of the clap-rs repository
# (https://github.com/clap-rs/clap). Provide its path via the CLAP_REPO
# environment variable or as the first argument:
#
#   CLAP_REPO=/path/to/clap tools/gen_clap_universe.sh
#   tools/gen_clap_universe.sh /path/to/clap
#
# We read $CLAP_REPO/tests/builder/*.rs.
set -euo pipefail

clap_repo="${1:-${CLAP_REPO:-}}"
if [ -z "$clap_repo" ]; then
  echo "error: path to the clap-rs checkout is required" >&2
  echo "       set CLAP_REPO or pass it as the first argument, e.g.:" >&2
  echo "       CLAP_REPO=/path/to/clap $0" >&2
  exit 2
fi

src="$clap_repo/tests/builder"
if [ ! -d "$src" ]; then
  echo "error: $src not found (is CLAP_REPO a clap-rs checkout?)" >&2
  exit 2
fi

out="$(cd "$(dirname "$0")/.." && pwd)/tests/clap_universe.zig"

{
  echo "//! GENERATED by tools/gen_clap_universe.sh from clap's tests/builder/*.rs"
  echo "//! (https://github.com/clap-rs/clap/tree/master/tests/builder)."
  echo "//! The complete set of clap builder test functions — the coverage"
  echo "//! denominator. Do not hand-edit; track our status in tests/coverage.zig."
  echo ""
  echo "pub const Test = struct { file: []const u8, name: []const u8 };"
  echo ""
  echo "pub const tests = [_]Test{"
  for f in "$src"/*.rs; do
    awk -v file="$(basename "$f")" '
      /^#\[test\]/ { t = 1; next }
      t && /^fn [a-zA-Z0-9_]+/ {
        name = $2; sub(/\(.*/, "", name)
        printf "    .{ .file = \"%s\", .name = \"%s\" },\n", file, name
        t = 0
      }
    ' "$f"
  done
  echo "};"
} > "$out"

echo "wrote $out ($(grep -c '\.name' "$out") tests)"
